name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests with Jest
      run: npm test -- --coverage

    - name: Run acceptance tests with Cypress
      run: npm run cy:run

    - name: Checkout code for SonarQube
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: http://localhost:9000
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: -X
