name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests with Jest
      run: npm test -- --coverage

  #  - name: Run acceptance tests with Cypress
  #    run: npm run cy:run
    
    - name: Download Code Climate CLI
      run: |
        curl -L https://github.com/codeclimate/codeclimate/releases/download/0.95.0/codeclimate-linux-amd64-0.95.0.tar.gz | tar xz
  
    - name: Run Code Climate Analysis
      run: |
        ./codeclimate analyze --dev